"""
pipeline.py

End-to-end ticket triage pipeline:
  1. Load tickets from data/sample_tickets.json
  2. For each ticket: classify (category/urgency/sentiment/escalation) via a local LLM
  3. Retrieve relevant knowledge base context (TF-IDF similarity search)
  4. Draft a grounded suggested response via the local LLM
  5. Write results to data/processed_tickets.json
  6. Generate a summary report (data/report.html)

Requires Ollama running locally (free, no account, no API key):
    1. Install: https://ollama.com/download
    2. Pull the model once: ollama pull llama3.2
    3. Run: python src/pipeline.py
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

from ai_client import OllamaConnectionError, SupportAIClient
from knowledge_base import KnowledgeBase

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"
KB_DIR = PROJECT_ROOT / "knowledge_base"


def load_tickets(path: Path) -> list[dict]:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def process_tickets(tickets: list[dict], ai: SupportAIClient, kb: KnowledgeBase) -> list[dict]:
    results = []
    total = len(tickets)
    for i, ticket in enumerate(tickets, start=1):
        print(f"[{i}/{total}] Processing {ticket['ticket_id']}: {ticket['subject'][:50]}...")

        classification = ai.classify_ticket(
            subject=ticket["subject"],
            body=ticket["body"],
            customer_tier=ticket.get("customer_tier", "standard"),
        )

        kb_chunks = kb.search(f"{ticket['subject']} {ticket['body']}", top_k=2)
        kb_context = kb.format_context(kb_chunks)

        draft = ai.draft_response(
            subject=ticket["subject"],
            body=ticket["body"],
            kb_context=kb_context,
        )

        results.append({
            **ticket,
            "category": classification.category,
            "urgency": classification.urgency,
            "sentiment": classification.sentiment,
            "escalate": classification.escalate,
            "escalation_reason": classification.escalation_reason,
            "kb_sources_used": [c.source for c in kb_chunks],
            "suggested_response": draft,
        })

        time.sleep(0.3)  # gentle pacing to avoid rate limit bursts

    return results


def generate_report(results: list[dict], output_path: Path) -> None:
    total = len(results)
    escalated = [r for r in results if r["escalate"]]
    by_category: dict[str, int] = {}
    by_urgency: dict[str, int] = {}
    for r in results:
        by_category[r["category"]] = by_category.get(r["category"], 0) + 1
        by_urgency[r["urgency"]] = by_urgency.get(r["urgency"], 0) + 1

    urgency_order = ["critical", "high", "medium", "low"]
    urgency_rows = "".join(
        f"<tr><td>{u}</td><td>{by_urgency.get(u, 0)}</td></tr>" for u in urgency_order
    )
    category_rows = "".join(
        f"<tr><td>{cat}</td><td>{count}</td></tr>" for cat, count in sorted(by_category.items())
    )
    escalation_rows = "".join(
        f"<tr><td>{r['ticket_id']}</td><td>{r['subject']}</td>"
        f"<td>{r['escalation_reason'] or ''}</td></tr>"
        for r in escalated
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Support Ticket Triage Report</title>
<style>
  body {{ font-family: -apple-system, Arial, sans-serif; max-width: 900px; margin: 40px auto; color: #1a1a1a; }}
  h1 {{ font-size: 1.6rem; }}
  h2 {{ font-size: 1.2rem; margin-top: 2rem; border-bottom: 2px solid #eee; padding-bottom: 0.3rem; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 0.5rem; }}
  th, td {{ text-align: left; padding: 8px 10px; border-bottom: 1px solid #eee; }}
  th {{ background: #f5f5f7; }}
  .stat {{ display: inline-block; margin-right: 2rem; }}
  .stat-num {{ font-size: 2rem; font-weight: 700; }}
  .escalated {{ color: #c0392b; font-weight: 600; }}
</style>
</head>
<body>
  <h1>Support Ticket Triage Report</h1>
  <p>Generated by the AI-assisted triage pipeline. {total} tickets processed.</p>

  <div>
    <div class="stat"><div class="stat-num">{total}</div>Total tickets</div>
    <div class="stat"><div class="stat-num escalated">{len(escalated)}</div>Escalations flagged</div>
  </div>

  <h2>By Urgency</h2>
  <table><tr><th>Urgency</th><th>Count</th></tr>{urgency_rows}</table>

  <h2>By Category</h2>
  <table><tr><th>Category</th><th>Count</th></tr>{category_rows}</table>

  <h2>Escalations</h2>
  <table><tr><th>Ticket ID</th><th>Subject</th><th>Reason</th></tr>{escalation_rows or '<tr><td colspan="3">None</td></tr>'}</table>
</body>
</html>
"""
    output_path.write_text(html, encoding="utf-8")


def main():
    tickets_path = DATA_DIR / "sample_tickets.json"
    output_path = DATA_DIR / "processed_tickets.json"
    report_path = DATA_DIR / "report.html"

    print("Loading tickets and knowledge base...")
    tickets = load_tickets(tickets_path)
    kb = KnowledgeBase(KB_DIR)

    try:
        ai = SupportAIClient()
    except OllamaConnectionError as e:
        print(f"\nError: {e}", file=sys.stderr)
        sys.exit(1)

    results = process_tickets(tickets, ai, kb)

    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"\nProcessed results written to {output_path}")

    generate_report(results, report_path)
    print(f"Summary report written to {report_path}")

    escalated_count = sum(1 for r in results if r["escalate"])
    print(f"\nDone. {len(results)} tickets processed, {escalated_count} flagged for escalation.")


if __name__ == "__main__":
    main()
